-- Per-test och per-flagga kolumner (OH-squat-mönster). Kör mot AI screening DB.
-- Synkad med src/lib/movementAssessment/supabaseFlatRow.ts (FLAT_ASSESSMENT_COLUMN_KEYS).

alter table public.movement_assessment_results
  add column if not exists ror_ankle_v numeric(8, 3),
  add column if not exists ror_ankle_h numeric(8, 3),
  add column if not exists ror_ankle_poang numeric(6, 2),
  add column if not exists ror_slr_v numeric(8, 3),
  add column if not exists ror_slr_h numeric(8, 3),
  add column if not exists ror_slr_poang numeric(6, 2),
  add column if not exists ror_hip_flex_v numeric(8, 3),
  add column if not exists ror_hip_flex_h numeric(8, 3),
  add column if not exists ror_hip_flex_poang numeric(6, 2),
  add column if not exists ror_hip_abd_v numeric(8, 3),
  add column if not exists ror_hip_abd_h numeric(8, 3),
  add column if not exists ror_hip_abd_poang numeric(6, 2),
  add column if not exists ror_hip_med_sup_v numeric(8, 3),
  add column if not exists ror_hip_med_sup_h numeric(8, 3),
  add column if not exists ror_hip_med_sup_poang numeric(6, 2),
  add column if not exists ror_hip_lat_sup_v numeric(8, 3),
  add column if not exists ror_hip_lat_sup_h numeric(8, 3),
  add column if not exists ror_hip_lat_sup_poang numeric(6, 2),
  add column if not exists ror_shoulder_pos_v numeric(8, 3),
  add column if not exists ror_shoulder_pos_h numeric(8, 3),
  add column if not exists ror_shoulder_pos_poang numeric(6, 2),
  add column if not exists ror_sh_med_v numeric(8, 3),
  add column if not exists ror_sh_med_h numeric(8, 3),
  add column if not exists ror_sh_med_poang numeric(6, 2),
  add column if not exists ror_sh_lat_v numeric(8, 3),
  add column if not exists ror_sh_lat_h numeric(8, 3),
  add column if not exists ror_sh_lat_poang numeric(6, 2),
  add column if not exists ror_arm_raise_v numeric(8, 3),
  add column if not exists ror_arm_raise_h numeric(8, 3),
  add column if not exists ror_arm_raise_poang numeric(6, 2),
  add column if not exists ror_side_flex_v numeric(8, 3),
  add column if not exists ror_side_flex_h numeric(8, 3),
  add column if not exists ror_side_flex_poang numeric(6, 2),
  add column if not exists ror_neck_side_v numeric(8, 3),
  add column if not exists ror_neck_side_h numeric(8, 3),
  add column if not exists ror_neck_side_poang numeric(6, 2),
  add column if not exists ror_hip_med_st_v numeric(8, 3),
  add column if not exists ror_hip_med_st_h numeric(8, 3),
  add column if not exists ror_hip_med_st_poang numeric(6, 2),
  add column if not exists ror_hip_lat_st_v numeric(8, 3),
  add column if not exists ror_hip_lat_st_h numeric(8, 3),
  add column if not exists ror_hip_lat_st_poang numeric(6, 2),
  add column if not exists ror_long_hf_v numeric(8, 3),
  add column if not exists ror_long_hf_h numeric(8, 3),
  add column if not exists ror_long_hf_poang numeric(6, 2),
  add column if not exists ror_ub_rot_v numeric(8, 3),
  add column if not exists ror_ub_rot_h numeric(8, 3),
  add column if not exists ror_ub_rot_poang numeric(6, 2),
  add column if not exists ror_neck_rot_v numeric(8, 3),
  add column if not exists ror_neck_rot_h numeric(8, 3),
  add column if not exists ror_neck_rot_poang numeric(6, 2),
  add column if not exists ror_oh_squat_grad numeric(8, 3),
  add column if not exists ror_oh_squat_poang numeric(6, 2),
  add column if not exists ror_oh_reach_kod text,
  add column if not exists ror_oh_reach_poang numeric(6, 2);

alter table public.movement_assessment_results
  add column if not exists hallning_forward_head boolean,
  add column if not exists hallning_thoracic_kyphosis boolean,
  add column if not exists hallning_straightened_thoracic boolean,
  add column if not exists hallning_scoliosis boolean,
  add column if not exists hallning_lumbar_lordosis boolean,
  add column if not exists hallning_flattened_lumbar boolean,
  add column if not exists hallning_anterior_pelvic_tilt boolean,
  add column if not exists hallning_posterior_pelvic_tilt boolean,
  add column if not exists hallning_high_ilium boolean,
  add column if not exists hallning_pelvic_torsion boolean,
  add column if not exists hallning_rounded_shoulders boolean,
  add column if not exists hallning_winging_scapula boolean,
  add column if not exists hallning_bow_legs boolean,
  add column if not exists hallning_knock_knees boolean,
  add column if not exists hallning_excessive_pronation boolean,
  add column if not exists hallning_excessive_supination boolean;

alter table public.movement_assessment_results
  add column if not exists karna_andning_kod text,
  add column if not exists karna_sekvens_kod text,
  add column if not exists karna_lumb_vinkel_kod text,
  add column if not exists karna_lumb_reps integer,
  add column if not exists karna_hals_grad integer,
  add column if not exists karna_poang_andning numeric(6, 2),
  add column if not exists karna_poang_sekvens numeric(6, 2),
  add column if not exists karna_poang_lumb numeric(6, 2),
  add column if not exists karna_poang_hals numeric(6, 2);

alter table public.movement_assessment_results
  add column if not exists stab_pinne_transversal_v boolean,
  add column if not exists stab_pinne_transversal_h boolean,
  add column if not exists stab_pinne_frontal_v boolean,
  add column if not exists stab_pinne_frontal_h boolean,
  add column if not exists stab_pinne_sagittal boolean,
  add column if not exists stab_pinne_axlar_v boolean,
  add column if not exists stab_pinne_axlar_h boolean,
  add column if not exists stab_pinne_becken_hoft boolean,
  add column if not exists stab_pinne_poang numeric(6, 2),
  add column if not exists stab_lunge_fot_v boolean,
  add column if not exists stab_lunge_fot_h boolean,
  add column if not exists stab_lunge_kna_v boolean,
  add column if not exists stab_lunge_kna_h boolean,
  add column if not exists stab_lunge_hoft_v boolean,
  add column if not exists stab_lunge_hoft_h boolean,
  add column if not exists stab_lunge_uk_v boolean,
  add column if not exists stab_lunge_uk_h boolean,
  add column if not exists stab_lunge_hallning_v boolean,
  add column if not exists stab_lunge_hallning_h boolean,
  add column if not exists stab_lunge_poang numeric(6, 2);
