-- Per-sida poängkolumner för bilaterala rörlighetstester.
-- Synkad med src/lib/movementAssessment/supabaseFlatRow.ts (`ror_<key>_poang_v/h`).

alter table public.movement_assessment_results
  add column if not exists ror_ankle_poang_v numeric(6, 2),
  add column if not exists ror_ankle_poang_h numeric(6, 2),
  add column if not exists ror_slr_poang_v numeric(6, 2),
  add column if not exists ror_slr_poang_h numeric(6, 2),
  add column if not exists ror_hip_flex_poang_v numeric(6, 2),
  add column if not exists ror_hip_flex_poang_h numeric(6, 2),
  add column if not exists ror_hip_abd_poang_v numeric(6, 2),
  add column if not exists ror_hip_abd_poang_h numeric(6, 2),
  add column if not exists ror_hip_med_sup_poang_v numeric(6, 2),
  add column if not exists ror_hip_med_sup_poang_h numeric(6, 2),
  add column if not exists ror_hip_lat_sup_poang_v numeric(6, 2),
  add column if not exists ror_hip_lat_sup_poang_h numeric(6, 2),
  add column if not exists ror_shoulder_pos_poang_v numeric(6, 2),
  add column if not exists ror_shoulder_pos_poang_h numeric(6, 2),
  add column if not exists ror_sh_med_poang_v numeric(6, 2),
  add column if not exists ror_sh_med_poang_h numeric(6, 2),
  add column if not exists ror_sh_lat_poang_v numeric(6, 2),
  add column if not exists ror_sh_lat_poang_h numeric(6, 2),
  add column if not exists ror_arm_raise_poang_v numeric(6, 2),
  add column if not exists ror_arm_raise_poang_h numeric(6, 2),
  add column if not exists ror_side_flex_poang_v numeric(6, 2),
  add column if not exists ror_side_flex_poang_h numeric(6, 2),
  add column if not exists ror_neck_side_poang_v numeric(6, 2),
  add column if not exists ror_neck_side_poang_h numeric(6, 2),
  add column if not exists ror_hip_med_st_poang_v numeric(6, 2),
  add column if not exists ror_hip_med_st_poang_h numeric(6, 2),
  add column if not exists ror_hip_lat_st_poang_v numeric(6, 2),
  add column if not exists ror_hip_lat_st_poang_h numeric(6, 2),
  add column if not exists ror_long_hf_poang_v numeric(6, 2),
  add column if not exists ror_long_hf_poang_h numeric(6, 2),
  add column if not exists ror_ub_rot_poang_v numeric(6, 2),
  add column if not exists ror_ub_rot_poang_h numeric(6, 2),
  add column if not exists ror_neck_rot_poang_v numeric(6, 2),
  add column if not exists ror_neck_rot_poang_h numeric(6, 2);
